// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: nothing/nothing.proto

package pbNothing

type NothingServiceClient interface{}

type NothingServiceServer interface {
	mustEmbedUnimplementedNothingServiceServer()
}
