// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: order-svc/order_service.proto

package pbOrder

import (
	context "context"
	grpc "google.golang.org/grpc"
)

const (
	OrderService_ListOrders_FullMethodName = "/example.order.OrderService/ListOrders"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
	// Counts orders grouped by status using ListOrdersRequest filters (paging is ignored).
	CountOrdersByStatus(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*CountOrdersByStatusResponse, error)
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	// A deliberately long doc comment, spanning several paragraphs, because a
	// brace-counting scanner that does not strip comments first will miscount
	// here and swallow the method below.
	//
	// It also contains prose with braces {like this} and parentheses (like
	// this), which is exactly the shape that breaks a naive parser.
	//
	// Real generated files carry comments like this whenever the .proto has
	// doc comments on its rpcs, so the parser must survive them.
	CountOrdersByStatus(context.Context, *ListOrdersRequest) (*CountOrdersByStatusResponse, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}
