// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: feed/feed_service.proto

package pbFeed

type FeedServiceClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type FeedServiceServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedFeedServiceServer()
}
