import * as assert from 'assert';
import { Pipeline, PROVIDER_STAGES, COMMAND_STAGES } from '../../src/core/pipeline';
import { Loc, Logger, LspClient, Pos } from '../../src/core/types';

const SILENT: Logger = { trace: () => undefined, error: () => undefined };

const PB_PATH = '/r/pb/echo_grpc.pb.go';
const PB_TEXT = [
  '// Code generated by protoc-gen-go-grpc. DO NOT EDIT.',
  '// source: pb/echo.proto',
  '',
  'package pb',
  '',
  'type EchoServiceClient interface {',
  '\tEcho(ctx context.Context, in *EchoRequest) (*EchoResponse, error)',
  '}',
  '',
  'type EchoServiceServer interface {',
  '\tEcho(context.Context, *EchoRequest) (*EchoResponse, error)',
  '}',
].join('\n');

const CLIENT_LINE = 6;
const SERVER_LINE = 10;

class FakeLsp implements LspClient {
  definitionCalls = 0;
  implementationCalls = 0;

  constructor(
    private readonly defs: Loc[] = [],
    private readonly impls: Loc[] = [],
  ) {}

  async definitions(_p: string, _pos: Pos): Promise<Loc[]> {
    this.definitionCalls++;
    return this.defs;
  }

  async implementations(_p: string, _pos: Pos): Promise<Loc[]> {
    this.implementationCalls++;
    return this.impls;
  }

  async references(): Promise<Loc[]> {
    return [];
  }

  async documentText(path: string): Promise<string | undefined> {
    return path === PB_PATH ? PB_TEXT : undefined;
  }

  async lineText(): Promise<string | undefined> {
    return undefined;
  }
}

describe('Pipeline.siteAt', () => {
  it('resolves directly when the cursor is already inside the generated file', async () => {
    const lsp = new FakeLsp();
    const p = new Pipeline(lsp, SILENT);
    const r = await p.siteAt(PB_PATH, { line: CLIENT_LINE, character: 1 }, PROVIDER_STAGES);
    assert.strictEqual(r?.site.method, 'Echo');
    assert.strictEqual(r?.site.role, 'client');
    assert.strictEqual(lsp.definitionCalls, 0, 'self stage must not call gopls');
  });

  it('follows a definition from a call site into the client interface', async () => {
    const lsp = new FakeLsp([{ path: PB_PATH, line: CLIENT_LINE, character: 1 }]);
    const p = new Pipeline(lsp, SILENT);
    const r = await p.siteAt('/r/biz/order.go', { line: 94, character: 40 }, PROVIDER_STAGES);
    assert.strictEqual(r?.pbPath, PB_PATH);
    assert.strictEqual(r?.site.role, 'client');
    assert.strictEqual(r?.site.serverMethod?.line, SERVER_LINE);
  });

  it('does not run the implementation stage for providers', async () => {
    const lsp = new FakeLsp([], [{ path: PB_PATH, line: SERVER_LINE, character: 1 }]);
    const p = new Pipeline(lsp, SILENT);
    const r = await p.siteAt('/r/mnt/handler.go', { line: 47, character: 30 }, PROVIDER_STAGES);
    assert.strictEqual(r, undefined);
    assert.strictEqual(lsp.implementationCalls, 0);
  });

  it('recognises a handler method when the implementation stage is allowed', async () => {
    const lsp = new FakeLsp([], [{ path: PB_PATH, line: SERVER_LINE, character: 1 }]);
    const p = new Pipeline(lsp, SILENT);
    const r = await p.siteAt('/r/mnt/handler.go', { line: 47, character: 30 }, COMMAND_STAGES);
    assert.strictEqual(r?.site.role, 'server');
    assert.strictEqual(r?.site.clientMethod?.line, CLIENT_LINE);
  });

  it('ignores definitions that land outside a generated grpc file', async () => {
    const lsp = new FakeLsp([{ path: '/r/biz/other.go', line: 1, character: 1 }]);
    const p = new Pipeline(lsp, SILENT);
    assert.strictEqual(
      await p.siteAt('/r/biz/order.go', { line: 94, character: 40 }, PROVIDER_STAGES),
      undefined,
    );
  });

  it('parses each generated file once until invalidated', async () => {
    let reads = 0;
    const lsp = new FakeLsp([{ path: PB_PATH, line: CLIENT_LINE, character: 1 }]);
    const orig = lsp.documentText.bind(lsp);
    lsp.documentText = async (path: string) => {
      reads++;
      return orig(path);
    };
    const p = new Pipeline(lsp, SILENT);
    await p.siteAt('/r/biz/a.go', { line: 1, character: 1 }, PROVIDER_STAGES);
    await p.siteAt('/r/biz/b.go', { line: 1, character: 1 }, PROVIDER_STAGES);
    assert.strictEqual(reads, 1);
    p.invalidate();
    await p.siteAt('/r/biz/c.go', { line: 1, character: 1 }, PROVIDER_STAGES);
    assert.strictEqual(reads, 2);
  });
});
